name: "Pull Request Docs Check"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"
    - name: directly build sphinx
      run: |
        pip install -r requirements.txt
        sphinx-build -D todo_include_todos=0 docs ./docs/_build/html/